export const icons = {
  menu: require('../assets/ic_menu.png'),
  bell: require('../assets/ic_bell.png'),
  chevronDown: require('../assets/ic_chevron_down.png'),
  chevronRight: require('../assets/ic_arrow_right.png'),
  arrowLeft: require('../assets/ic_arrow_left.png'),
  box: require('../assets/ic_box.png'),
  layout: require('../assets/ic_layout.png'),
  home: require('../assets/tab_home.png'),
  tag: require('../assets/ic_tag.png'),
  shoppingBag: require('../assets/ic_shopping_bag.png'),
  alertCircle: require('../assets/ic_alert_circle.png'),
  activity: require('../assets/ic_activity.png'),
  store: require('../assets/ic_store.png'),
  transfer: require('../assets/ic_transfer.png'),
  delivery: require('../assets/ic_delivery.png'),
  history: require('../assets/ic_history.png'),
  user: require('../assets/ic_user.png'),
  search: require('../assets/ic_search.png'),
  filter: require('../assets/ic_filter.png'),
  plus: require('../assets/ic_plus.png'),
  edit: require('../assets/ic_edit.png'),
  trash: require('../assets/ic_trash.png'),
  check: require('../assets/ic_check.png'),
  refresh: require('../assets/ic_refresh.png'),
  report: require('../assets/ic_report.png'),
  tabInventory: require('../assets/tab_inventory.png'),
  tabOrders: require('../assets/tab_orders.png'),
  tabProfile: require('../assets/tab_profile.png'),
} as const;

export type IconName = keyof typeof icons;
